// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJNGC7YFvI370eORV7W6aZr_HI9ekAiV8',
    appId: '1:404172957296:web:5d45b2f253ac294d85b6b5',
    messagingSenderId: '404172957296',
    projectId: 'screens-b97ca',
    authDomain: 'screens-b97ca.firebaseapp.com',
    storageBucket: 'screens-b97ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKJzhMad8Fwzz8WRQnF_s0ibuBbtkiG04',
    appId: '1:404172957296:android:d80d42001d001ace85b6b5',
    messagingSenderId: '404172957296',
    projectId: 'screens-b97ca',
    storageBucket: 'screens-b97ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf3TPolmd9O3OLHmUod6prE7bNKGcJnKU',
    appId: '1:404172957296:ios:46b3e13a88cac89b85b6b5',
    messagingSenderId: '404172957296',
    projectId: 'screens-b97ca',
    storageBucket: 'screens-b97ca.appspot.com',
    iosClientId: '404172957296-35t3s0ruf1rrpl5364pfoeltlel9lnuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf3TPolmd9O3OLHmUod6prE7bNKGcJnKU',
    appId: '1:404172957296:ios:0c80e1bac33a610c85b6b5',
    messagingSenderId: '404172957296',
    projectId: 'screens-b97ca',
    storageBucket: 'screens-b97ca.appspot.com',
    iosClientId: '404172957296-r6qlt7v6efi38os268jgrbkssfssmunk.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
